export default { items : [
    "Burger Buns",
    "Hot Dog",
    "Kale and Feta Cheese Sandwich with Garlic Aioli",
    "Pasta Salad",
    "Pulled Pork Sandwich",
    "Roasted Chicken",
    "Salad",
    "Sausage",
    "Steak",
    "Tacos",
    "Turkey Sandwich",
    "Veggie Burger",
    "Wings",
  ],
  prices : [
    "$2.99",
    "$3.99",
    "$4.99",
    "$5.99",
    "$6.99",
    "$7.99",
    "$8.99",
    "$9.99",
    "$10.99",
    "$11.99",
    "$12.99",
    "$13.99",
    "$14.99",
  ],
  testerItems : [
    {
      name: "Checken Pot Pie Autn Nona Made In Montego Bay",
      expiry_date: "2022-12-31",
      ai: false,
      category: "Fridge",
      quantity: 1,
    },
    {
      name: "Eggs",
      expiry_date: "2022-12-31",
      ai: false,
      category: "Fridge",
      quantity: 2
    },
    {
      name: "Bread",
      expiry_date: "2022-12-31",
      ai: false,
      category: "Pantry",
      quantity: 3
    },
    {
      name: "Chicken",
      expiry_date: "2022-12-31",
      ai: false,
      category: "Freezer",
      quantity: 3
    },
  ]};